name: build-and-deploy-snapshot
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy-snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          scope: "@danwulff"
      - run: npm ci
      - run: npm run build
