name: publish-version-after-merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency:
  group: publish-version-after-merge

jobs:
  publish-version-after-merge:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          scope: "@danwulff"
      - name: Install dependencies
        run: npm ci
      - name: Build Styles & Components
        run: npm run build
      - name: Publish package version
        run: npm run publish-version -- ${{ github.event.pull_request.number }} '${{ toJson(github.event.pull_request.labels.*.name) }}'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
